# ---------------- CHINESE MENU (1-20) ----------------
chinese_menu = {
    1:  {"name": "Veg Manchurian",              "price": 180},
    2:  {"name": "Chicken Manchurian",          "price": 220},
    3:  {"name": "Veg Fried Rice",               "price": 150},
    4:  {"name": "Chicken Fried Rice",           "price": 200},
    5:  {"name": "Veg Noodles",                  "price": 150},
    6:  {"name": "Chicken Noodles",              "price": 210},
    7:  {"name": "Veg Spring Roll",              "price": 140},
    8:  {"name": "Chicken Spring Roll",          "price": 190},
    9:  {"name": "Chilli Chicken",               "price": 240},
    10: {"name": "Chilli Paneer",                "price": 200},
    11: {"name": "Veg Manchow Soup",             "price": 120},
    12: {"name": "Chicken Manchow Soup",         "price": 150},
    13: {"name": "Hot & Sour Soup (Veg)",        "price": 110},
    14: {"name": "Hot & Sour Soup (Chicken)",    "price": 140},
    15: {"name": "Schezwan Fried Rice",          "price": 190},
    16: {"name": "Schezwan Noodles",             "price": 190},
    17: {"name": "Chicken Lollipop",             "price": 260},
    18: {"name": "Veg Momos",                    "price": 130},
    19: {"name": "Chicken Momos",                "price": 170},
    20: {"name": "American Chopsuey",            "price": 210},
}

# ---------------- RICE MEAL MENU (21-40) ----------------
rice_meal = {
    21: {"name": "Steamed Rice",         "price": 100},
    22: {"name": "Jeera Rice",           "price": 130},
    23: {"name": "Veg Pulao",            "price": 160},
    24: {"name": "Paneer Pulao",         "price": 190},
    25: {"name": "Chicken Biryani",      "price": 260},
    26: {"name": "Mutton Biryani",       "price": 320},
    27: {"name": "Veg Biryani",          "price": 190},
    28: {"name": "Egg Biryani",          "price": 210},
    29: {"name": "Curd Rice",            "price": 120},
    30: {"name": "Lemon Rice",           "price": 130},
    31: {"name": "Tomato Rice",          "price": 130},
    32: {"name": "Kashmiri Pulao",       "price": 200},
    33: {"name": "Peas Pulao",           "price": 150},
    34: {"name": "Ghee Rice",            "price": 140},
    35: {"name": "Fried Rice (Plain)",   "price": 140},
    36: {"name": "Vegetable Khichdi",    "price": 150},
    37: {"name": "Prawn Biryani",        "price": 300},
    38: {"name": "Hyderabadi Biryani",   "price": 280},
    39: {"name": "Coconut Rice",         "price": 140},
    40: {"name": "Schezwan Rice Bowl",   "price": 180},
}

# ---------------- CHICKEN MEAL MENU (41-60) ----------------
chicken_meal = {
    41: {"name": "Butter Chicken",             "price": 280},
    42: {"name": "Chicken Tikka Masala",       "price": 290},
    43: {"name": "Chicken Curry",              "price": 240},
    44: {"name": "Chicken Korma",              "price": 270},
    45: {"name": "Kadai Chicken",              "price": 260},
    46: {"name": "Chicken Do Pyaza",           "price": 250},
    47: {"name": "Chicken Tikka",              "price": 270},
    48: {"name": "Tandoori Chicken (Half)",    "price": 260},
    49: {"name": "Tandoori Chicken (Full)",    "price": 480},
    50: {"name": "Chicken Malai Tikka",        "price": 290},
    51: {"name": "Chicken Seekh Kabab",        "price": 250},
    52: {"name": "Chicken Chettinad",          "price": 270},
    53: {"name": "Chicken 65",                 "price": 220},
    54: {"name": "Chicken Lababdar",           "price": 280},
    55: {"name": "Chicken Handi",              "price": 300},
    56: {"name": "Chicken Angara",             "price": 290},
    57: {"name": "Chicken Reshmi Kabab",       "price": 260},
    58: {"name": "Grilled Chicken",            "price": 250},
    59: {"name": "Chicken Roast",              "price": 240},
    60: {"name": "Chicken Popcorn",            "price": 180},
}

# ---------------- DRINK MENU (61-80) ----------------
drink_menu = {
    61: {"name": "Mineral Water (1L)",         "price": 40},
    62: {"name": "Soft Drink (Coke/Pepsi)",    "price": 60},
    63: {"name": "Sprite",                     "price": 60},
    64: {"name": "Fresh Lime Soda",            "price": 70},
    65: {"name": "Masala Chaas",               "price": 60},
    66: {"name": "Lassi (Sweet)",              "price": 90},
    67: {"name": "Lassi (Salted)",             "price": 80},
    68: {"name": "Mango Lassi",                "price": 110},
    69: {"name": "Iced Tea",                   "price": 90},
    70: {"name": "Cold Coffee",                "price": 120},
    71: {"name": "Hot Tea",                    "price": 40},
    72: {"name": "Hot Coffee",                 "price": 50},
    73: {"name": "Fresh Orange Juice",         "price": 110},
    74: {"name": "Watermelon Juice",           "price": 100},
    75: {"name": "Mixed Fruit Juice",          "price": 130},
    76: {"name": "Mocktail (Virgin Mojito)",   "price": 150},
    77: {"name": "Mocktail (Blue Lagoon)",     "price": 160},
    78: {"name": "Milkshake (Chocolate)",      "price": 140},
    79: {"name": "Milkshake (Vanilla)",        "price": 130},
    80: {"name": "Buttermilk",                 "price": 50},
}