# ---------------- CHINESE MENU ----------------
chinese_menu = {
    "Veg Manchurian": 180,
    "Chicken Manchurian": 220,
    "Veg Fried Rice": 150,
    "Chicken Fried Rice": 200,
    "Veg Noodles": 150,
    "Chicken Noodles": 210,
    "Veg Spring Roll": 140,
    "Chicken Spring Roll": 190,
    "Chilli Chicken": 240,
    "Chilli Paneer": 200,
    "Veg Manchow Soup": 120,
    "Chicken Manchow Soup": 150,
    "Hot & Sour Soup (Veg)": 110,
    "Hot & Sour Soup (Chicken)": 140,
    "Schezwan Fried Rice": 190,
    "Schezwan Noodles": 190,
    "Chicken Lollipop": 260,
    "Veg Momos": 130,
    "Chicken Momos": 170,
    "American Chopsuey": 210,
}

# ---------------- RICE MEAL MENU ----------------
rice_meal = {
    "Steamed Rice": 100,
    "Jeera Rice": 130,
    "Veg Pulao": 160,
    "Paneer Pulao": 190,
    "Chicken Biryani": 260,
    "Mutton Biryani": 320,
    "Veg Biryani": 190,
    "Egg Biryani": 210,
    "Curd Rice": 120,
    "Lemon Rice": 130,
    "Tomato Rice": 130,
    "Kashmiri Pulao": 200,
    "Peas Pulao": 150,
    "Ghee Rice": 140,
    "Fried Rice (Plain)": 140,
    "Vegetable Khichdi": 150,
    "Prawn Biryani": 300,
    "Hyderabadi Biryani": 280,
    "Coconut Rice": 140,
    "Schezwan Rice Bowl": 180,
}

# ---------------- CHICKEN MEAL MENU ----------------
chicken_meal = {
    "Butter Chicken": 280,
    "Chicken Tikka Masala": 290,
    "Chicken Curry": 240,
    "Chicken Korma": 270,
    "Kadai Chicken": 260,
    "Chicken Do Pyaza": 250,
    "Chicken Tikka": 270,
    "Tandoori Chicken (Half)": 260,
    "Tandoori Chicken (Full)": 480,
    "Chicken Malai Tikka": 290,
    "Chicken Seekh Kabab": 250,
    "Chicken Chettinad": 270,
    "Chicken 65": 220,
    "Chicken Lababdar": 280,
    "Chicken Handi": 300,
    "Chicken Angara": 290,
    "Chicken Reshmi Kabab": 260,
    "Grilled Chicken": 250,
    "Chicken Roast": 240,
    "Chicken Popcorn": 180,
}

# ---------------- DRINK MENU ----------------
drink_menu = {
    "Mineral Water (1L)": 40,
    "Soft Drink (Coke/Pepsi)": 60,
    "Sprite": 60,
    "Fresh Lime Soda": 70,
    "Masala Chaas": 60,
    "Lassi (Sweet)": 90,
    "Lassi (Salted)": 80,
    "Mango Lassi": 110,
    "Iced Tea": 90,
    "Cold Coffee": 120,
    "Hot Tea": 40,
    "Hot Coffee": 50,
    "Fresh Orange Juice": 110,
    "Watermelon Juice": 100,
    "Mixed Fruit Juice": 130,
    "Mocktail (Virgin Mojito)": 150,
    "Mocktail (Blue Lagoon)": 160,
    "Milkshake (Chocolate)": 140,
    "Milkshake (Vanilla)": 130,
    "Buttermilk": 50,
}